=== dsteige1/digitale_karten/data/datenbank.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT datenbank (event+)>
<!ELEMENT event (id,location,veranstaltung)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT location (gaststaette, lat, long)>
<!ELEMENT gaststaette (#PCDATA)>
<!ELEMENT lat (#PCDATA)>
<!ELEMENT long (#PCDATA)>
<!ELEMENT veranstaltung (name, daten,gastgeber,teilnehmerzahl, eintritt)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT daten (datum,uhrzeit,tag)>
<!ELEMENT datum (#PCDATA)>
<!ELEMENT uhrzeit (#PCDATA)>
<!ELEMENT tag (#PCDATA)>
<!ELEMENT gastgeber (#PCDATA)>
<!ELEMENT teilnehmerzahl (teilgenommen, interessiert)>
<!ELEMENT teilgenommen (#PCDATA)>
<!ELEMENT interessiert (#PCDATA)>
<!ELEMENT eintritt (#PCDATA)>

=== dsteige1/digitale_karten/data/datensatz.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE datenbank SYSTEM "datenbank.dtd">
<datenbank>
    <event>
        <id>1</id>
        <location>
            <gaststaette>Heinz Gaul</gaststaette>
            <lat>50.9496813</lat>
            <long>6.9120946</long>
        </location>
        <veranstaltung>
            <name>King Kong Kicks – Das erste Mal mit Achtzehn </name>
            <daten>
                <datum>2018-01-05</datum>
                <uhrzeit>23:00</uhrzeit>
                <tag>Freitag</tag>
            </daten>
            <gastgeber>King Kong Kicks</gastgeber>
            <teilnehmerzahl>
                <teilgenommen>172</teilgenommen>
                <interessiert>216</interessiert>
            </teilnehmerzahl>
            <eintritt>10</eintritt>
        </veranstaltung>
    </event>
    <event>
        <id>2</id>
        <location>
            <gaststaette>Heinz Gaul</gaststaette>
            <lat>50.9496813</lat>
            <long>6.9120946</long>
        </location>
        <veranstaltung>
            <name>Drop That! 4th Anniversary at Heinz Gaul </name>
            <daten>
                <datum>2018-01-06</datum>
                <uhrzeit>23:30</uhrzeit>
                <tag>Samstag</tag>
            </daten>
            <gastgeber>Drop That Cologne</gastgeber>
            <teilnehmerzahl>
                <teilgenommen>452</teilgenommen>
                <interessiert>898</interessiert>
            </teilnehmerzahl>
            <eintritt>13</eintritt>
        </veranstaltung>
    </event>
    <event>
        <id>3</id>
        <location>
            <gaststaette>Heinz Gaul</gaststaette>
            <lat>50.9496813</lat>
            <long>6.9120946</long>
        </location>
        <veranstaltung>
            <name>Weird Sounds w/ Giorgia Angiuli</name>
            <daten>
                <datum>2018-01-12</datum>
                <uhrzeit>23:00</uhrzeit>
                <tag>Freitag</tag>
            </daten>
            <gastgeber>Heinz Gaul</gastgeber>
            <teilnehmerzahl>
                <teilgenommen>196</teilgenommen>
                <interessiert>757</interessiert>
            </teilnehmerzahl>
            <eintritt>13</eintritt>
        </veranstaltung>
    </event>
    <event>
        <id>4</id>
        <location>
            <gaststaette>Heinz Gaul</gaststaette>
            <lat>50.9496813</lat>
            <long>6.9120946</long>
        </location>
        <veranstaltung>
            <name>Trash Island </name>
            <daten>
                <datum>2018-01-13</datum>
                <uhrzeit>22:00</uhrzeit>
                <tag>Samstag</tag>
            </daten>
            <gastgeber>Trash Island Party</gastgeber>
            <teilnehmerzahl>
                <teilgenommen>368</teilgenommen>
                <interessiert>1198</interessiert>
            </teilnehmerzahl>
            <eintritt>10</eintritt>
        </veranstaltung>
    </event>
    <event>
        <id>5</id>
        <location>
            <gaststaette>Heinz Gaul</gaststaette>
            <lat>50.9496813</lat>
            <long>6.9120946</long>
        </location>
        <veranstaltung>
            <name>Hip Hop Evolution</name>
            <daten>
                <datum>2018-01-19</datum>
                <uhrzeit>23:00</uhrzeit>
                <tag>Freitag</tag>
            </daten>
            <gastgeber>Beatsmart</gastgeber>
            <teilnehmerzahl>
                <teilgenommen>54</teilgenommen>
                <interessiert>679</interessiert>
            </teilnehmerzahl>
            <eintritt>13</eintritt>
        </veranstaltung>
    </event>
    <event>
        <id>6</id>
        <location>
            <gaststaette>Heinz Gaul</gaststaette>
            <lat>50.9496813</lat>
            <long>6.9120946</long>
        </location>
        <veranstaltung>
            <name>Festival d’electronique</name>
            <daten>
                <datum>2018-01-20</datum>
                <uhrzeit>22:00</uhrzeit>
                <tag>Samstag</tag>
            </daten>
            <gastgeber>Lichtblick</gastgeber>
            <teilnehmerzahl>
                <teilgenommen>733</teilgenommen>
                <interessiert>5889</interessiert>
            </teilnehmerzahl>
            <eintritt>18</eintritt>
        </veranstaltung>
    </event>
    <event>
        <id>7</id>
        <location>
            <gaststaette>Heinz Gaul</gaststaette>
            <lat>50.9496813</lat>
            <long>6.9120946</long>
        </location>
        <veranstaltung>
            <name>ZIRKUS BEATZARR</name>
            <daten>
                <datum>2018-01-26</datum>
                <uhrzeit>23:00</uhrzeit>
                <tag>Freitag</tag>
            </daten>
            <gastgeber>Zirkus Beatzarr</gastgeber>
            <teilnehmerzahl>
                <teilgenommen>264</teilgenommen>
                <interessiert>684</interessiert>
            </teilnehmerzahl>
            <eintritt>12</eintritt>
        </veranstaltung>
    </event>
    <event>
        <id>8</id>
        <location>
            <gaststaette>Heinz Gaul</gaststaette>
            <lat>50.9496813</lat>
            <long>6.9120946</long>
        </location>
        <veranstaltung>
            <name> Kitball Showcase w/ Tube &amp; Berger, Hanne &amp; Lore, Juliet Sikora </name>
            <daten>
                <datum>2018-01-27</datum>
                <uhrzeit>23:00</uhrzeit>
                <tag>Samstag</tag>
            </daten>
            <gastgeber>Heinz Gaul</gastgeber>
            <teilnehmerzahl>
                <teilgenommen>210</teilgenommen>
                <interessiert>1315</interessiert>
            </teilnehmerzahl>
            <eintritt>12</eintritt>
        </veranstaltung>
    </event>
    <event>
        <id>9</id>
        <location>
            <gaststaette>Heinz Gaul</gaststaette>
            <lat>50.9496813</lat>
            <long>6.9120946</long>
        </location>
        <veranstaltung>
            <name>RAW Night w/ I Hate Models, Tim Tama &amp; Rezystor</name>
            <daten>
                <datum>2018-02-02</datum>
                <uhrzeit>23:00</uhrzeit>
                <tag>Freitag</tag>
            </daten>
            <gastgeber>Electronic Love</gastgeber>
            <teilnehmerzahl>
                <teilgenommen>303</teilgenommen>
                <interessiert>1558</interessiert>
            </teilnehmerzahl>
            <eintritt>15</eintritt>
        </veranstaltung>
    </event>
    <event>
        <id>10</id>
        <location>
            <gaststaette>Heinz Gaul</gaststaette>
            <lat>50.9496813</lat>
            <long>6.9120946</long>
        </location>
        <veranstaltung>
            <name>Schwerelos 2000er &amp; Wir singen 90er</name>
            <daten>
                <datum>2018-02-03</datum>
                <uhrzeit>22:00</uhrzeit>
                <tag>Samstag</tag>
            </daten>
            <gastgeber>Trash Island Party</gastgeber>
            <teilnehmerzahl>
                <teilgenommen>89</teilgenommen>
                <interessiert>688</interessiert>
            </teilnehmerzahl>
            <eintritt>10</eintritt>
        </veranstaltung>
    </event>
    <event>
        <id>11</id>
        <location>
            <gaststaette>Heinz Gaul</gaststaette>
            <lat>50.9496813</lat>
            <long>6.9120946</long>
        </location>
        <veranstaltung>
            <name>Trash Island at Heinz Gaul am Karnevalsfreitag</name>
            <daten>
                <datum>2018-02-09</datum>
                <uhrzeit>20:00</uhrzeit>
                <tag>Freitag</tag>
            </daten>
            <gastgeber>Trash Island Party</gastgeber>
            <teilnehmerzahl>
                <teilgenommen>365</teilgenommen>
                <interessiert>1962</interessiert>
            </teilnehmerzahl>
            <eintritt>12</eintritt>
        </veranstaltung>
    </event>
    <event>
        <id>12</id>
        <location>
            <gaststaette>Heinz Gaul</gaststaette>
            <lat>50.9496813</lat>
            <long>6.9120946</long>
        </location>
        <veranstaltung>
            <name>Advanced Karneval mit Extrawelt live &amp; Freunden</name>
            <daten>
                <datum>2018-02-10</datum>
                <uhrzeit>23:30</uhrzeit>
                <tag>Samstag</tag>
            </daten>
            <gastgeber>Advanced Cologne</gastgeber>
            <teilnehmerzahl>
                <teilgenommen>291</teilgenommen>
                <interessiert>2047</interessiert>
            </teilnehmerzahl>
            <eintritt>12</eintritt>
        </veranstaltung>
    </event>
    <event>
        <id>13</id>
        <location>
            <gaststaette>Heinz Gaul</gaststaette>
            <lat>50.9496813</lat>
            <long>6.9120946</long>
        </location>
        <veranstaltung>
            <name>Art of House w/ Kotelett &amp; Zadak (Katermukke), Heinz Gaul</name>
            <daten>
                <datum>17.02.2018</datum>
                <uhrzeit>23:00</uhrzeit>
                <tag>Samstag</tag>
            </daten>
            <gastgeber>Heinz Gaul</gastgeber>
            <teilnehmerzahl>
                <teilgenommen>234</teilgenommen>
                <interessiert>1411</interessiert>
            </teilnehmerzahl>
            <eintritt>15</eintritt>
        </veranstaltung>
    </event>
    <event>
        <id>14</id>
        <location>
            <gaststaette>Heinz Gaul</gaststaette>
            <lat>50.9496813</lat>
            <long>6.9120946</long>
        </location>
        <veranstaltung>
            <name>Beats x Bass x Gaul • Weekender: Sascha Cawa (Katermukke) + TC (OWSLA, UK)</name>
            <daten>
                <datum>2018-02-23</datum>
                <uhrzeit>23:00</uhrzeit>
                <tag>Freitag</tag>
            </daten>
            <gastgeber>Heinz Gaul</gastgeber>
            <teilnehmerzahl>
